# This is a basic workflow to help you get started with Actions

name: cd

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate_latex_files:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: jupyter pandoc texlive-xetex python-jedi
          version: 0.1

      - name: Generate LaTeX files
        run: python scripts/jupyter_notebook_to_latex.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generated LaTeX files
          branch: generated-latex
          push_options: '--force'
          create_branch: true

  generate_pdf:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          ref: generated-latex
      
      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_use_xelatex: true
          work_in_root_file_dir: true
          root_file: '**/main.tex'
          glob_root_file: true

      - run: |
          find . -type f,l ! -iwholename "./.git/*" ! -iname "*.pdf" -delete
          touch .nojekyll

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Deployed PDFs from `generated-latex`
          branch: gh-pages
          push_options: '--force'    
          create_branch: true
